version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "actions/checkout"
        versions: [">=6.0.2"]
      - dependency-name: "actions/setup-node"
        versions: [">=6.2.0"]
      - dependency-name: "peter-evans/create-pull-request"
        versions: [">=8.0.0"]
